
version: '3'

services:
  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    environment:
      - TZ=America/Mexico_City
    env_file:
      - ./.envDB

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - mongodb
    command: gunicorn -w 1 -b 0.0.0.0:5005 app:app
  
  nginx-1:
    restart: always
    build: ./nginx
    ports:
      - "8082:8082"
    depends_on:
      - api
  